application: addressbook-001
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /css/(.*\.css)$
  static_files: css/\1
  upload: css/(.*\.css)$
  mime_type: text/css
- url: /templates/(.*\.js)$
  static_files: templates/\1
  upload: templates/(.*\.js)$
  mime_type: application/x-javascript
- url: .*
  script: main.app
